development:
  adapter: postgresql
  encoding: unicode
  database: homesite_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: homesite_test
  password: 123
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: homesite_production
  host: 127.0.0.1
  pool: 5
  username: homesite
  password: mazafaka
